language: node_js
node_js:
- '0.10'
before_script:
- bower install
env:
  global:
  - secure: jtjcflSmWkQJMqiRksC4tzhpqsYA4kSupt8JHkjJBF2AAdknJ+5d3X/N3EfVqr5yGMO8ODFGG14SRK8R+mz18pfPrPqjfh415ksK3w0+nZCcbovlAoC9j64BqtzJcbGpxbhrXsyzKaCz6Q2J7GfemVCjIo4vMjTZOXWAQPc0jek=
  - GH_OWNER: Axonn
  - GH_PROJECT_NAME: videojs-overlay-plugin
after_success:
- if git checkout master; then git checkout -b master; fi
- cp build/js/vjsoverlayplugin.js vjsoverlayplugin.js
- cp build/js/vjsoverlayplugin.d.ts vjsoverlayplugin.d.ts
- git add -f vjsoverlayplugin.js
- git add -f vjsoverlayplugin.d.ts
- git config user.name "travis-ci"
- git config user.email "corwin.tomkinson@adfero.co.uk"
- git commit -am "add build files to master [ci skip]"
- git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:master > /dev/null 2>&1
  
